services:

  postgres-local:
    image: postgres:15.2
    restart: always
    container_name: postgres-local
    ports:
      - "5454:5432"
    volumes:
      - postgresql-local:/var/lib/postgresql/data
    env_file:
      - fastapi-app/.env

  redis-local:
    image: redis:7.0.10
    restart: always
    container_name: redis-local
    volumes:
      - redis-local:/data/
    ports:
      - '6377:6379'

  selenium-local:
    image: selenium/standalone-chrome:134.0-chromedriver-134.0-20250303
    restart: always
    container_name: selenium-local
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: '2gb'

volumes:
  postgresql-local:
  redis-local:

