"""create companies table

Revision ID: 2bc3cd49e79e
Revises:
Create Date: 2025-03-05 00:21:58.175555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2bc3cd49e79e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column(
            "name",
            postgresql.ENUM(
                "AVIASALES", "SELECTEL", "X5", name="company_name"
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("company_url", sa.String(length=2000), nullable=True),
        sa.Column("company_vacs_url", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("company_pkey")),
        sa.UniqueConstraint(
            "company_vacs_url", name=op.f("company_company_vacs_url_key")
        ),
        sa.UniqueConstraint("name", name=op.f("company_name_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company")
    # ### end Alembic commands ###
